ArtPollReply minimum packet length requirements bug fix
jsimonetti/go-artnet pull request #39
Opened 2024-06-03 02:14 UTC by jmbarzee

Quick Fix - A better implementation would support the extension struct

ArtPollReply now complies with minimum packet length requirements of ArtNet-4 

[art-net.pdf](https://art-net.org.uk/downloads/art-net.pdf) - ArtPollReply - Minimum Packet Length
> Consumers of ArtPollReply shall accept as valid a packet of length 207

2024-06-03 17:40 UTC, jsimonetti commented
Could you please sign off on your commit?
I will have a look after. Thanks!

2024-06-03 17:58 UTC, jmbarzee commented
@jsimonetti Can you clarify what you want? Do you just want an email signature on the commit message?

2024-06-03 18:02 UTC, jmbarzee commented
Ahhh, I got my answer from the work flow. Thanks!

2024-06-05 00:07 UTC, jmbarzee commented
@jsimonetti I ended up needing a bunch of stuff in the extension so I implemented the rest of the packet. Should also support minimum size packets now.

2024-06-25 06:42 UTC, jsimonetti requested changes

2024-06-25 06:42 UTC, jsimonetti commented on packet/code/status3.go
> +// WithFailSafe returns how the node will behave in the
This looks like a copy paste error

2024-06-25 06:43 UTC, jsimonetti commented
My apologies for the late reply.

Thank you for your contribution. Unfortunately I have no way to test the extra fields, but the code looks good enough to me.
Just a small nit and then I can merge.

2025-10-24 11:36 UTC, jsimonetti commented
Closing for now due to being stale.

2025-10-24 11:36 UTC, closed without merging